"""Initial IPRESS schema derived from the SQLAlchemy ORM models.

Revision ID: 20260909_0001
Revises:
Create Date: 2026-09-09

This revision is intentionally explicit and frozen.  It is the installation
source of truth; schema_mysql_salud.sql remains a domain reference only.
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "20260909_0001"
down_revision = None
branch_labels = None
depends_on = None

def _seed_minimum_catalogs() -> None:
    """Insert the minimum reference values needed by the application."""
    op.bulk_insert(
        sa.table("tipos_documento", sa.column("codigo", sa.String), sa.column("nombre", sa.String)),
        [
            {"codigo": "DNI", "nombre": "Documento Nacional de Identidad"},
            {"codigo": "CE", "nombre": "Carné de Extranjería"},
            {"codigo": "PAS", "nombre": "Pasaporte"},
            {"codigo": "DE", "nombre": "Documento de Extranjero"},
            {"codigo": "OTRO", "nombre": "Otro documento"},
        ],
    )
    op.bulk_insert(
        sa.table("sexos", sa.column("codigo", sa.String), sa.column("nombre", sa.String)),
        [
            {"codigo": "F", "nombre": "FEMENINO"},
            {"codigo": "M", "nombre": "MASCULINO"},
            {"codigo": "I", "nombre": "INTERSEXUAL"},
        ],
    )
    op.bulk_insert(
        sa.table("seguros", sa.column("codigo", sa.String), sa.column("nombre", sa.String)),
        [
            {"codigo": "SIN_SEGURO", "nombre": "SIN SEGURO"},
            {"codigo": "SIS", "nombre": "SIS"},
            {"codigo": "ESSALUD", "nombre": "EsSalud"},
            {"codigo": "PARTICULAR", "nombre": "Particular"},
            {"codigo": "OTRO", "nombre": "Otro"},
        ],
    )
    op.bulk_insert(
        sa.table("modalidades_atencion", sa.column("codigo", sa.String), sa.column("nombre", sa.String)),
        [
            {"codigo": "AMBULATORIA", "nombre": "Ambulatoria"},
            {"codigo": "EMERGENCIA", "nombre": "Emergencia"},
        ],
    )
    op.bulk_insert(
        sa.table("grupos_etarios", sa.column("codigo", sa.String), sa.column("nombre", sa.String)),
        [
            {"codigo": "NINO", "nombre": "Niño"},
            {"codigo": "ADOLESCENTE", "nombre": "Adolescente"},
            {"codigo": "ADULTO", "nombre": "Adulto"},
            {"codigo": "ADULTO_MAYOR", "nombre": "Adulto mayor"},
        ],
    )
    op.bulk_insert(
        sa.table("roles", sa.column("codigo", sa.String), sa.column("nombre", sa.String)),
        [
            {"codigo": "ADMIN", "nombre": "Administrador"},
            {"codigo": "REGISTRO", "nombre": "Registro de pacientes"},
            {"codigo": "PROFESIONAL", "nombre": "Profesional de salud"},
            {"codigo": "AUDITOR", "nombre": "Auditor de solo lectura"},
        ],
    )


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cie10',
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('categoria', sa.String(length=200), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('(TRUE)'), nullable=False),
    sa.PrimaryKeyConstraint('codigo'),
    mysql_engine='InnoDB'
    )
    op.create_table('disa',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('(TRUE)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo', name='uq_disa_codigo'),
    mysql_engine='InnoDB'
    )
    op.create_table('especialidades',
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('grupo', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('(TRUE)'), nullable=False),
    sa.PrimaryKeyConstraint('codigo'),
    mysql_engine='InnoDB'
    )
    op.create_table('grupos_etarios',
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('edad_minima_meses', mysql.SMALLINT(unsigned=True), nullable=True),
    sa.Column('edad_maxima_meses', mysql.SMALLINT(unsigned=True), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('(TRUE)'), nullable=False),
    sa.PrimaryKeyConstraint('codigo'),
    mysql_engine='InnoDB'
    )
    op.create_table('grupos_riesgo',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('(TRUE)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo', name='uq_grupos_riesgo_codigo'),
    mysql_engine='InnoDB'
    )
    op.create_table('modalidades_atencion',
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('(TRUE)'), nullable=False),
    sa.PrimaryKeyConstraint('codigo'),
    mysql_engine='InnoDB'
    )
    op.create_table('prestaciones',
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=False),
    sa.Column('grupo', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('(TRUE)'), nullable=False),
    sa.PrimaryKeyConstraint('codigo'),
    mysql_engine='InnoDB'
    )
    op.create_table('profesiones',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('(TRUE)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', name='uq_profesiones_nombre'),
    mysql_engine='InnoDB'
    )
    op.create_table('roles',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo', name='uq_roles_codigo'),
    mysql_engine='InnoDB'
    )
    op.create_table('seguros',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('(TRUE)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo', name='uq_seguros_codigo'),
    sa.UniqueConstraint('nombre', name='uq_seguros_nombre'),
    mysql_engine='InnoDB'
    )
    op.create_table('sexos',
    sa.Column('codigo', sa.CHAR(length=1), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('(TRUE)'), nullable=False),
    sa.PrimaryKeyConstraint('codigo'),
    mysql_engine='InnoDB'
    )
    op.create_table('tipos_documento',
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('(TRUE)'), nullable=False),
    sa.PrimaryKeyConstraint('codigo'),
    mysql_engine='InnoDB'
    )
    op.create_table('ubigeos',
    sa.Column('codigo', sa.CHAR(length=6), nullable=False),
    sa.Column('departamento', sa.String(length=100), nullable=False),
    sa.Column('provincia', sa.String(length=100), nullable=False),
    sa.Column('distrito', sa.String(length=100), nullable=False),
    sa.Column('localidad', sa.String(length=150), nullable=True),
    sa.Column('altitud_msnm', mysql.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('quintil', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('codigo'),
    mysql_engine='InnoDB'
    )
    op.create_index('idx_ubigeos_distrito', 'ubigeos', ['distrito'], unique=False)
    op.create_table('profesionales',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('codigo_legacy', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('numero_documento', sa.String(length=30), nullable=True),
    sa.Column('nombre_completo', sa.String(length=200), nullable=False),
    sa.Column('profesion_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('colegiatura', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('(TRUE)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['profesion_id'], ['profesiones.id'], name='fk_profesionales_profesion', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_legacy', name='uq_profesionales_legacy'),
    sa.UniqueConstraint('numero_documento', name='uq_profesionales_documento'),
    mysql_engine='InnoDB'
    )
    op.create_table('redes',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('id_disa', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('(TRUE)'), nullable=False),
    sa.ForeignKeyConstraint(['id_disa'], ['disa.id'], name='fk_redes_disa', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_disa', 'codigo', name='uq_redes_disa_codigo'),
    mysql_engine='InnoDB'
    )
    op.create_table('microredes',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('id_red', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('(TRUE)'), nullable=False),
    sa.ForeignKeyConstraint(['id_red'], ['redes.id'], name='fk_microredes_red', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_red', 'codigo', name='uq_microredes_red_codigo'),
    mysql_engine='InnoDB'
    )
    op.create_table('profesional_especialidades',
    sa.Column('profesional_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('especialidad_codigo', sa.String(length=20), nullable=False),
    sa.Column('es_principal', sa.Boolean(), server_default=sa.text('(FALSE)'), nullable=False),
    sa.ForeignKeyConstraint(['especialidad_codigo'], ['especialidades.codigo'], name='fk_profesional_especialidades_especialidad', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['profesional_id'], ['profesionales.id'], name='fk_profesional_especialidades_profesional', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('profesional_id', 'especialidad_codigo'),
    mysql_engine='InnoDB'
    )
    op.create_table('usuarios',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('profesional_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('nombre_usuario', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('(TRUE)'), nullable=False),
    sa.Column('ultimo_acceso_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['profesional_id'], ['profesionales.id'], name='fk_usuarios_profesional', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_usuario', name='uq_usuarios_nombre_usuario'),
    sa.UniqueConstraint('profesional_id', name='uq_usuarios_profesional'),
    mysql_engine='InnoDB'
    )
    op.create_table('auditoria',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('usuario_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('tabla_nombre', sa.String(length=100), nullable=False),
    sa.Column('registro_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('accion', sa.String(length=20), nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('datos_anteriores', sa.JSON(), nullable=True),
    sa.Column('datos_nuevos', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='fk_auditoria_usuario', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index('idx_auditoria_fecha', 'auditoria', ['fecha'], unique=False)
    op.create_index('idx_auditoria_tabla_registro', 'auditoria', ['tabla_nombre', 'registro_id'], unique=False)
    op.create_table('establecimientos',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('codigo_legacy', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('id_microred', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('codigo_renaes', sa.String(length=30), nullable=True),
    sa.Column('codigo_ideess', sa.String(length=30), nullable=True),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('abreviatura', sa.String(length=50), nullable=True),
    sa.Column('ubigeo_codigo', sa.CHAR(length=6), nullable=True),
    sa.Column('area_urbana', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('(TRUE)'), nullable=False),
    sa.ForeignKeyConstraint(['id_microred'], ['microredes.id'], name='fk_establecimientos_microred', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ubigeo_codigo'], ['ubigeos.codigo'], name='fk_establecimientos_ubigeo', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_ideess', name='uq_establecimientos_ideess'),
    sa.UniqueConstraint('codigo_legacy', name='uq_establecimientos_legacy'),
    sa.UniqueConstraint('codigo_renaes', name='uq_establecimientos_renaes'),
    mysql_engine='InnoDB'
    )
    op.create_index('idx_establecimientos_nombre', 'establecimientos', ['nombre'], unique=False)
    op.create_table('usuario_roles',
    sa.Column('usuario_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('rol_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], name='fk_usuario_roles_rol', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='fk_usuario_roles_usuario', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('usuario_id', 'rol_id'),
    mysql_engine='InnoDB'
    )
    op.create_table('consultorios',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('establecimiento_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('consultorio_padre_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('especialidad_codigo', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('(TRUE)'), nullable=False),
    sa.ForeignKeyConstraint(['consultorio_padre_id'], ['consultorios.id'], name='fk_consultorios_padre', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['especialidad_codigo'], ['especialidades.codigo'], name='fk_consultorios_especialidad', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['establecimiento_id'], ['establecimientos.id'], name='fk_consultorios_establecimiento', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('establecimiento_id', 'codigo', name='uq_consultorios_establecimiento_codigo'),
    mysql_engine='InnoDB'
    )
    op.create_index('idx_consultorios_padre', 'consultorios', ['consultorio_padre_id'], unique=False)
    op.create_table('pacientes',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('codclie_legacy', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('historia_clinica', sa.String(length=255), nullable=True),
    sa.Column('historia_familiar', sa.Text(), nullable=True),
    sa.Column('tipo_documento_codigo', sa.String(length=10), nullable=False),
    sa.Column('numero_documento', sa.String(length=30), nullable=False),
    sa.Column('fecha_inscripcion', sa.Date(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('apellido_paterno', sa.String(length=100), nullable=True),
    sa.Column('apellido_materno', sa.String(length=100), nullable=True),
    sa.Column('primer_nombre', sa.String(length=100), nullable=True),
    sa.Column('otros_nombres', sa.String(length=150), nullable=True),
    sa.Column('sexo_codigo', sa.CHAR(length=1), nullable=True),
    sa.Column('ubigeo_residencia_codigo', sa.CHAR(length=6), nullable=True),
    sa.Column('localidad', sa.String(length=150), nullable=True),
    sa.Column('direccion', sa.String(length=300), nullable=True),
    sa.Column('establecimiento_registro_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('seguro_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('telefono_principal', sa.String(length=30), nullable=True),
    sa.Column('condicion', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.Boolean(), server_default=sa.text('(TRUE)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['establecimiento_registro_id'], ['establecimientos.id'], name='fk_pacientes_establecimiento', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seguro_id'], ['seguros.id'], name='fk_pacientes_seguro', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sexo_codigo'], ['sexos.codigo'], name='fk_pacientes_sexo', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tipo_documento_codigo'], ['tipos_documento.codigo'], name='fk_pacientes_tipo_documento', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ubigeo_residencia_codigo'], ['ubigeos.codigo'], name='fk_pacientes_ubigeo', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codclie_legacy', name='uq_pacientes_codclie_legacy'),
    sa.UniqueConstraint('tipo_documento_codigo', 'numero_documento', name='uq_pacientes_documento'),
    mysql_engine='InnoDB'
    )
    op.create_index('idx_pacientes_historia', 'pacientes', ['historia_clinica'], unique=False)
    op.create_index('idx_pacientes_nombres', 'pacientes', ['apellido_paterno', 'apellido_materno', 'primer_nombre'], unique=False)
    op.create_table('atenciones',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('codigo_legacy', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('paciente_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('establecimiento_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('profesional_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('especialidad_codigo', sa.String(length=20), nullable=True),
    sa.Column('consultorio_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('modalidad_atencion_codigo', sa.String(length=20), nullable=False),
    sa.Column('grupo_etario_codigo', sa.String(length=20), nullable=False),
    sa.Column('fecha_atencion', sa.DateTime(), nullable=False),
    sa.Column('fecha_atendido', sa.DateTime(), nullable=True),
    sa.Column('historia_clinica_snapshot', sa.String(length=255), nullable=True),
    sa.Column('edad_anios', mysql.SMALLINT(unsigned=True), nullable=True),
    sa.Column('peso_kg', mysql.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('talla_cm', mysql.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('perimetro_abdominal_cm', mysql.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('presion_sistolica', mysql.SMALLINT(unsigned=True), nullable=True),
    sa.Column('presion_diastolica', mysql.SMALLINT(unsigned=True), nullable=True),
    sa.Column('temperatura_c', mysql.DECIMAL(precision=4, scale=1), nullable=True),
    sa.Column('pe', sa.String(length=50), nullable=True),
    sa.Column('te', sa.String(length=50), nullable=True),
    sa.Column('pt', sa.String(length=50), nullable=True),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_fin', sa.Time(), nullable=True),
    sa.Column('admision', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default=sa.text("'ATENDIDO'"), nullable=False),
    sa.Column('created_by_usuario_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['consultorio_id'], ['consultorios.id'], name='fk_atenciones_consultorio', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_usuario_id'], ['usuarios.id'], name='fk_atenciones_creado_por', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['especialidad_codigo'], ['especialidades.codigo'], name='fk_atenciones_especialidad', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['establecimiento_id'], ['establecimientos.id'], name='fk_atenciones_establecimiento', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['grupo_etario_codigo'], ['grupos_etarios.codigo'], name='fk_atenciones_grupo_etario', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['modalidad_atencion_codigo'], ['modalidades_atencion.codigo'], name='fk_atenciones_modalidad', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], name='fk_atenciones_paciente', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['profesional_id'], ['profesionales.id'], name='fk_atenciones_profesional', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_legacy', name='uq_atenciones_codigo_legacy'),
    mysql_engine='InnoDB'
    )
    op.create_index('idx_atenciones_establecimiento_fecha', 'atenciones', ['establecimiento_id', 'fecha_atencion'], unique=False)
    op.create_index('idx_atenciones_paciente_fecha', 'atenciones', ['paciente_id', 'fecha_atencion'], unique=False)
    op.create_index('idx_atenciones_profesional_fecha', 'atenciones', ['profesional_id', 'fecha_atencion'], unique=False)
    op.create_table('consultorio_profesionales',
    sa.Column('consultorio_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('profesional_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('es_responsable', sa.Boolean(), server_default=sa.text('(FALSE)'), nullable=False),
    sa.ForeignKeyConstraint(['consultorio_id'], ['consultorios.id'], name='fk_consultorio_profesionales_consultorio', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['profesional_id'], ['profesionales.id'], name='fk_consultorio_profesionales_profesional', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('consultorio_id', 'profesional_id', 'fecha_inicio'),
    mysql_engine='InnoDB'
    )
    op.create_index('idx_consultorio_profesionales_vigencia', 'consultorio_profesionales', ['consultorio_id', 'fecha_inicio', 'fecha_fin'], unique=False)
    op.create_table('paciente_anexos_legacy',
    sa.Column('paciente_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('numero_anexo', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('tipo_origen', sa.String(length=20), server_default=sa.text("'TEXTO'"), nullable=False),
    sa.Column('valor_texto', sa.String(length=255), nullable=True),
    sa.Column('valor_booleano', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], name='fk_anexos_legacy_paciente', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('paciente_id', 'numero_anexo'),
    mysql_engine='InnoDB'
    )
    op.create_table('paciente_codigos_externos',
    sa.Column('paciente_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('sistema', sa.String(length=40), nullable=False),
    sa.Column('valor', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], name='fk_paciente_codigos_paciente', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('paciente_id', 'sistema'),
    mysql_engine='InnoDB'
    )
    op.create_table('paciente_grupos_riesgo',
    sa.Column('paciente_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('grupo_riesgo_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('observacion', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['grupo_riesgo_id'], ['grupos_riesgo.id'], name='fk_paciente_grupo_riesgo_grupo', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], name='fk_paciente_grupo_riesgo_paciente', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('paciente_id', 'grupo_riesgo_id', 'fecha_inicio'),
    mysql_engine='InnoDB'
    )
    op.create_index('idx_paciente_grupos_riesgo_activos', 'paciente_grupos_riesgo', ['paciente_id', 'fecha_fin'], unique=False)
    op.create_table('paciente_responsables',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('paciente_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('parentesco', sa.String(length=30), nullable=False),
    sa.Column('nombre_completo', sa.String(length=200), nullable=False),
    sa.Column('tipo_documento_codigo', sa.String(length=10), nullable=True),
    sa.Column('numero_documento', sa.String(length=30), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('es_principal', sa.Boolean(), server_default=sa.text('(FALSE)'), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('(TRUE)'), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], name='fk_paciente_responsables_paciente', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tipo_documento_codigo'], ['tipos_documento.codigo'], name='fk_paciente_responsables_tipo_documento', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index('idx_paciente_responsables_paciente', 'paciente_responsables', ['paciente_id', 'activo'], unique=False)
    op.create_table('atencion_diagnosticos',
    sa.Column('atencion_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('numero_orden', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('cie10_codigo', sa.String(length=20), nullable=False),
    sa.Column('tipo_diagnostico', sa.String(length=50), nullable=True),
    sa.Column('observacion', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['atencion_id'], ['atenciones.id'], name='fk_atencion_diagnosticos_atencion', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cie10_codigo'], ['cie10.codigo'], name='fk_atencion_diagnosticos_cie10', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('atencion_id', 'numero_orden'),
    mysql_engine='InnoDB'
    )
    op.create_index('idx_atencion_diagnosticos_cie10', 'atencion_diagnosticos', ['cie10_codigo'], unique=False)
    op.create_table('atencion_prestaciones',
    sa.Column('atencion_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('numero_orden', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('prestacion_codigo', sa.String(length=30), nullable=False),
    sa.Column('cantidad', mysql.DECIMAL(precision=8, scale=2), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['atencion_id'], ['atenciones.id'], name='fk_atencion_prestaciones_atencion', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['prestacion_codigo'], ['prestaciones.codigo'], name='fk_atencion_prestaciones_prestacion', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('atencion_id', 'numero_orden'),
    mysql_engine='InnoDB'
    )
    op.create_index('idx_atencion_prestaciones_codigo', 'atencion_prestaciones', ['prestacion_codigo'], unique=False)
    op.create_table('certificados',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('atencion_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('establecimiento_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('profesional_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('numero_certificado', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('consultorio', sa.String(length=100), nullable=True),
    sa.Column('admision', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default=sa.text("'EMITIDO'"), nullable=False),
    sa.ForeignKeyConstraint(['atencion_id'], ['atenciones.id'], name='fk_certificados_atencion', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['establecimiento_id'], ['establecimientos.id'], name='fk_certificados_establecimiento', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['profesional_id'], ['profesionales.id'], name='fk_certificados_profesional', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('establecimiento_id', 'numero_certificado', name='uq_certificados_eess_numero'),
    mysql_engine='InnoDB'
    )
    op.create_index('idx_certificados_atencion', 'certificados', ['atencion_id'], unique=False)
    op.create_table('evaluaciones_nutricionales',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('paciente_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('atencion_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('establecimiento_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('peso_kg', mysql.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('talla_cm', mysql.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('hemoglobina', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('fecha_hemoglobina', sa.Date(), nullable=True),
    sa.Column('edad_anios', mysql.SMALLINT(unsigned=True), nullable=True),
    sa.Column('edad_meses', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('edad_dias', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('edad_gestacional_semanas', mysql.SMALLINT(unsigned=True), nullable=True),
    sa.Column('perimetro_abdominal_cm', mysql.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('imc', mysql.DECIMAL(precision=6, scale=3), nullable=True),
    sa.Column('whz', mysql.DECIMAL(precision=6, scale=3), nullable=True),
    sa.Column('haz', mysql.DECIMAL(precision=6, scale=3), nullable=True),
    sa.Column('waz', mysql.DECIMAL(precision=6, scale=3), nullable=True),
    sa.Column('diagnostico_peso_edad', sa.String(length=100), nullable=True),
    sa.Column('diagnostico_talla_edad', sa.String(length=100), nullable=True),
    sa.Column('diagnostico_peso_talla', sa.String(length=100), nullable=True),
    sa.Column('diagnostico', sa.String(length=500), nullable=True),
    sa.Column('enviado', sa.Boolean(), server_default=sa.text('(FALSE)'), nullable=False),
    sa.ForeignKeyConstraint(['atencion_id'], ['atenciones.id'], name='fk_nutricion_atencion', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['establecimiento_id'], ['establecimientos.id'], name='fk_nutricion_establecimiento', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], name='fk_nutricion_paciente', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index('idx_nutricion_paciente_fecha', 'evaluaciones_nutricionales', ['paciente_id', 'fecha'], unique=False)
    op.create_index('idx_nutricion_tipo_fecha', 'evaluaciones_nutricionales', ['tipo', 'fecha'], unique=False)
    op.create_table('fua',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('atencion_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('numero_fua', sa.String(length=100), nullable=True),
    sa.Column('codigo_ciudad', sa.String(length=50), nullable=True),
    sa.Column('codigo_anio', sa.String(length=20), nullable=True),
    sa.Column('codigo_eess', sa.String(length=50), nullable=True),
    sa.Column('edad_declarada', sa.String(length=20), nullable=True),
    sa.Column('fecha_emision', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('estado', sa.String(length=30), server_default=sa.text("'BORRADOR'"), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['atencion_id'], ['atenciones.id'], name='fk_fua_atencion', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('atencion_id', name='uq_fua_atencion'),
    sa.UniqueConstraint('numero_fua', name='uq_fua_numero'),
    mysql_engine='InnoDB'
    )
    op.create_index('idx_fua_fecha_emision', 'fua', ['fecha_emision'], unique=False)
    op.create_table('referencias',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('atencion_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('numero_referencia', sa.String(length=100), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('establecimiento_origen_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('establecimiento_destino_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default=sa.text("'PENDIENTE'"), nullable=False),
    sa.ForeignKeyConstraint(['atencion_id'], ['atenciones.id'], name='fk_referencias_atencion', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['establecimiento_destino_id'], ['establecimientos.id'], name='fk_referencias_destino', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['establecimiento_origen_id'], ['establecimientos.id'], name='fk_referencias_origen', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_referencia', name='uq_referencias_numero'),
    mysql_engine='InnoDB'
    )
    op.create_index('idx_referencias_atencion', 'referencias', ['atencion_id'], unique=False)
    op.create_index('idx_referencias_destino_estado', 'referencias', ['establecimiento_destino_id', 'estado'], unique=False)
    op.create_table('vigilancia_sien',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('paciente_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('atencion_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('establecimiento_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('peso_kg', mysql.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('talla_cm', mysql.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('hemoglobina', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('fecha_hemoglobina', sa.Date(), nullable=True),
    sa.Column('enviado', sa.Boolean(), server_default=sa.text('(FALSE)'), nullable=False),
    sa.Column('estado', sa.String(length=30), server_default=sa.text("'PENDIENTE'"), nullable=False),
    sa.ForeignKeyConstraint(['atencion_id'], ['atenciones.id'], name='fk_sien_atencion', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['establecimiento_id'], ['establecimientos.id'], name='fk_sien_establecimiento', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], name='fk_sien_paciente', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index('idx_sien_paciente_fecha', 'vigilancia_sien', ['paciente_id', 'fecha'], unique=False)
    op.create_table('certificado_prestaciones',
    sa.Column('certificado_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('numero_orden', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('prestacion_codigo', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['certificado_id'], ['certificados.id'], name='fk_certificado_prestaciones_certificado', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['prestacion_codigo'], ['prestaciones.codigo'], name='fk_certificado_prestaciones_prestacion', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('certificado_id', 'numero_orden'),
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
    # Alembic wraps TextClause defaults in parentheses when rendering
    # ``create_table``. MySQL rejects ``DEFAULT (CURRENT_TIMESTAMP ON UPDATE
    # CURRENT_TIMESTAMP)``, so add the automatic-update clause after table
    # creation with native valid MySQL syntax.
    for table_name in ("profesionales", "usuarios", "pacientes", "atenciones"):
        op.execute(
            f"ALTER TABLE `{table_name}` MODIFY `updated_at` DATETIME NOT NULL "
            "DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"
        )
    _seed_minimum_catalogs()


def downgrade() -> None:
    # MySQL (1553) refuses to drop an index that still backs a foreign key which
    # adopted it as its own index, and every ``idx_*`` removed below belongs to
    # a table dropped immediately after it.  ``DROP TABLE`` already deletes the
    # table's indexes, so the initial schema only has to drop its tables.
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certificado_prestaciones')
    op.drop_table('vigilancia_sien')
    op.drop_table('referencias')
    op.drop_table('fua')
    op.drop_table('evaluaciones_nutricionales')
    op.drop_table('certificados')
    op.drop_table('atencion_prestaciones')
    op.drop_table('atencion_diagnosticos')
    op.drop_table('paciente_responsables')
    op.drop_table('paciente_grupos_riesgo')
    op.drop_table('paciente_codigos_externos')
    op.drop_table('paciente_anexos_legacy')
    op.drop_table('consultorio_profesionales')
    op.drop_table('atenciones')
    op.drop_table('pacientes')
    op.drop_table('consultorios')
    op.drop_table('usuario_roles')
    op.drop_table('establecimientos')
    op.drop_table('auditoria')
    op.drop_table('usuarios')
    op.drop_table('profesional_especialidades')
    op.drop_table('microredes')
    op.drop_table('redes')
    op.drop_table('profesionales')
    op.drop_table('ubigeos')
    op.drop_table('tipos_documento')
    op.drop_table('sexos')
    op.drop_table('seguros')
    op.drop_table('roles')
    op.drop_table('profesiones')
    op.drop_table('prestaciones')
    op.drop_table('modalidades_atencion')
    op.drop_table('grupos_riesgo')
    op.drop_table('grupos_etarios')
    op.drop_table('especialidades')
    op.drop_table('disa')
    op.drop_table('cie10')
    # ### end Alembic commands ###
